apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: circuitbreak
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: circuitbreak
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: frontend
  namespace: circuitbreak
spec:
  protocol: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: circuitbreak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/transparent-proxy: "true"
      labels:
        app: frontend
    spec:
      serviceAccountName: frontend
      containers:
        - name: frontend
          image: hashicorpdemoapp/frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_PUBLIC_API_URL
              value: "http://public-api:8080"
