apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: frontend
  namespace: circuitbreak
spec:
  destination:
    name: frontend
  sources:
    - name: nginx
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: public-api
  namespace: circuitbreak
spec:
  destination:
    name: public-api
  sources:
    - name: nginx
      action: allow
    - name: traffic-generator
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: product-api
  namespace: circuitbreak
spec:
  destination:
    name: product-api
  sources:
    - name: public-api
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: product-api-db
  namespace: circuitbreak
spec:
  destination:
    name: product-api-db
  sources:
    - name: product-api
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: payments
  namespace: circuitbreak
spec:
  destination:
    name: payments
  sources:
    - name: public-api
      action: allow
