apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

  - apps/nginx.yaml
  - apps/service-frontend.yaml
  - apps/public-api.yaml
  - apps/product-api.yaml
  - apps/product-api-db.yaml
  - apps/payments.yaml
  - apps/traffic-generator.yaml

  - consul/service-intentions.yaml
  - consul/servicedefaults-nginx.yaml
  - consul/servicedefaults-traffic-generator.yaml
